version: "3.1"
services:
    php8-webserver:
      container_name: php8-webserver
      build: docker/nginx
      working_dir: /application
      restart: on-failure
      volumes:
        - .:/application:cached
        - ./var/nginx_logs:/var/log/nginx
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php8-php-fpm
      labels:
        - traefik.http.routers.php8-webserver.rule=Host(`php8-webserver.box`)

    php8-php-fpm:
      container_name: php8-php-fpm
      build: docker/php-fpm
      working_dir: /application
      restart: on-failure
      volumes:
        - .:/application:cached
        - ./var/log:/application/var/log
        - ~/.ssh/:/root/.ssh/
      labels:
        - traefik.enable=false

networks:
  default:
    external:
      name: nirvana